services:
    config:
        build: ./Config/config-server
        container_name: config
        ports:
            - 8888:8888
        networks:
            - 'mynet'

    eureka:
        build: ./Gateway/eureka-server
        container_name: eureka
        ports:
            - 8761:8761
        networks:
            - 'mynet'
        depends_on:
            - config

    gateway:
        build: ./Gateway/gateway-server
        container_name: gateway
        ports:
            - 8080:8080
        networks:
            - 'mynet'
        depends_on:
            - eureka

    ordenes:
        build: ./Microservicios/orden
        container_name: ordenes
        expose:
            - '9060'
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/product_now
            - SPRING_DATASOURCE_USERNAME=appuser
            - SPRING_DATASOURCE_PASSWORD=apppass
        depends_on:
            - config
            - eureka
            - gateway
            - productos
            - mysql-db
        networks:
            - 'mynet'
    productos:
        build: ./Microservicios/producto
        container_name: productos
        expose:
            - '9070'
        networks:
            - 'mynet'
        environment:
            - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db-products:3306/movie_now
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=rootpassword
        depends_on:
            - config
            - eureka
            - gateway
            - mysql-db-products  

    mysql-db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: gestion_orden 
            MYSQL_USER: appuser
            MYSQL_PASSWORD: apppass
        volumes:
            - ./init-orden.sql:/docker-entrypoint-initdb.d/init-orden.sql
            - mysql-data:/var/lib/mysql
        ports:
            - "3308:3306"
        networks:
            - 'mynet'

    mysql-db-products:
        image: mysql:8.0
        networks:
            - 'mynet'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: gestion_producto 
            MYSQL_USER: productosuser
            MYSQL_PASSWORD: productospass
        volumes:
            - ./init-producto.sql:/docker-entrypoint-initdb.d/init-producto.sql
            - mysql-data-products:/var/lib/mysql
        ports:
            - "3307:3306"

volumes:
    mysql-data: 
    mysql-data-products:
networks:
    mynet:
        driver: bridge